CREATE TABLE USUARIO (
    EMAIL VARCHAR(50) PRIMARY KEY NOT NULL,
    TIPO VARCHAR(20) NOT NULL
);


CREATE TABLE SEGURO (
    ID SERIAL PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    ESTADO_ACTIVO BOOLEAN NOT NULL
);

CREATE TABLE PACIENTE (
    ID SERIAL PRIMARY KEY,
    CUI VARCHAR(24),
    CORREO VARCHAR(50) NOT NULL,
    ES_MUJER BOOLEAN NOT NULL,
    NOMBRES VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL,
    NOMBRE_CONTACTO1 VARCHAR(50) NOT NULL,
    PARENTESCO_CONTACTO1 VARCHAR(24) NOT NULL,
    TELEFONO_CONTACTO1 VARCHAR(20) NOT NULL,
    NOMBRE_CONTACTO2 VARCHAR(50),
    PARENTESCO_CONTACTO2 VARCHAR(24),
    TELEFONO_CONTACTO2 VARCHAR(20),
    TIPO_SANGRE VARCHAR(3) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    ID_SEGURO INTEGER,
    FECHA_NACIMIENTO DATE NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    FOREIGN KEY (ID_SEGURO) REFERENCES SEGURO (ID)
);



CREATE TABLE ESTUDIANTE (
    CARNET VARCHAR(20) NOT NULL,
    CARRERA VARCHAR(50) NOT NULL,
    ID_PACIENTE INTEGER NOT NULL,
    PRIMARY KEY (CARNET),
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE COLABORADOR (
    CODIGO VARCHAR(20) PRIMARY KEY NOT NULL,
    AREA VARCHAR(50) NOT NULL,
    ID_PACIENTE INTEGER NOT NULL,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE CONSULTA (
    ID SERIAL PRIMARY KEY NOT NULL,
    ID_PACIENTE INTEGER NOT NULL,
    FECHA TIMESTAMP NOT NULL,
    MOTIVO TEXT NOT NULL,
    FRECUENCIA_RESPIRATORIA VARCHAR(10),
    TEMPERATURA DOUBLE PRECISION,
    SATURACION_OXIGENO DOUBLE PRECISION,
    GLUCOMETRIA DOUBLE PRECISION,
    FRECUENCIA_CARDIACA DOUBLE PRECISION,
    PRESION_SISTOLICA INTEGER,
    PRESION_DIASTOLICA INTEGER,
    EVALUADOR VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID),
    FOREIGN KEY (EVALUADOR) REFERENCES USUARIO (EMAIL)
);

CREATE TABLE DIAGNOSTICO (
    ID SERIAL PRIMARY KEY NOT NULL,
    ID_CONSULTA INTEGER NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    TRATAMIENTO TEXT,
    FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTA (ID)
);

CREATE TABLE MEDICAMENTO (
    ID SERIAL PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    CANTIDAD INTEGER,
    ID_CONSULTA INTEGER NOT NULL,
    FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTA (ID)
);

CREATE TABLE ANTECEDENTES_FAMILIARES (
    ID_PACIENTE INTEGER PRIMARY KEY NOT NULL,
    HIPERTENSION_ARTERIAL BOOLEAN,
    HIPERTENSION_ARTERIAL_DATA JSON,
    DIABETES_MELLITUS BOOLEAN,
    DIABETES_MELLITUS_DATA JSON,
    HIPOTIROIDISMO BOOLEAN,
    HIPOTIROIDISMO_DATA JSON,
    ASMA BOOLEAN,
    ASMA_DATA JSON,
    CONVULSIONES BOOLEAN,
    CONVULSIONES_DATA JSON,
    INFARTO_AGUDO_MIOCARDIO BOOLEAN,
    INFARTO_AGUDO_MIOCARDIO_DATA JSON,
    CANCER BOOLEAN,
    CANCER_DATA JSON,
    ENFERMEDADES_CARDIACAS BOOLEAN,
    ENFERMEDADES_CARDIACAS_DATA JSON,
    ENFERMEDADES_RENALES BOOLEAN,
    ENFERMEDADES_RENALES_DATA JSON,
    OTROS BOOLEAN,
    OTROS_DATA JSON,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE ANTECEDENTES_PERSONALES (
    ID_PACIENTE INTEGER PRIMARY KEY NOT NULL,
    HIPERTENSION_ARTERIAL BOOLEAN,
    HIPERTENSION_ARTERIAL_DATA JSON,
    DIABETES_MELLITUS BOOLEAN,
    DIABETES_MELLITUS_DATA JSON,
    HIPOTIROIDISMO BOOLEAN,
    HIPOTIROIDISMO_DATA JSON,
    ASMA BOOLEAN,
    ASMA_DATA JSON,
    CONVULSIONES BOOLEAN,
    CONVULSIONES_DATA JSON,
    INFARTO_AGUDO_MIOCARDIO BOOLEAN,
    INFARTO_AGUDO_MIOCARDIO_DATA JSON,
    CANCER BOOLEAN,
    CANCER_DATA JSON,
    ENFERMEDADES_CARDIACAS BOOLEAN,
    ENFERMEDADES_CARDIACAS_DATA JSON,
    ENFERMEDADES_RENALES BOOLEAN,
    ENFERMEDADES_RENALES_DATA JSON,
    OTROS BOOLEAN,
    OTROS_DATA JSON,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE ANTECEDENTES_ALERGICOS (
    ID_PACIENTE INTEGER PRIMARY KEY NOT NULL,
    MEDICAMENTO BOOLEAN,
    MEDICAMENTO_DATA JSON,
    COMIDA BOOLEAN,
    COMIDA_DATA JSON,
    POLVO BOOLEAN,
    POLVO_DATA JSON,
    POLEN BOOLEAN,
    POLEN_DATA JSON,
    CAMBIO_DE_CLIMA BOOLEAN,
    CAMBIO_DE_CLIMA_DATA JSON,
    ANIMALES BOOLEAN,
    ANIMALES_DATA JSON,
    OTROS BOOLEAN,
    OTROS_DATA JSON,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE ANTECEDENTES_QUIRURGICOS (
    ID_PACIENTE INTEGER PRIMARY KEY NOT NULL,
    ANTECEDENTE_QUIRURGICO BOOLEAN,
    ANTECEDENTE_QUIRURGICO_DATA JSON,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE ANTECEDENTES_TRAUMATOLOGICOS (
    ID_PACIENTE INTEGER PRIMARY KEY NOT NULL,
    ANTECEDENTE_TRAUMATOLOGICO BOOLEAN,
    ANTECEDENTE_TRAUMATOLOGICO_DATA JSON,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE ANTECEDENTES_PSIQUIATRICOS (
    ID_PACIENTE INTEGER PRIMARY KEY NOT NULL,
    DEPRESION BOOLEAN,
    DEPRESION_DATA JSON,
    ANSIEDAD BOOLEAN,
    ANSIEDAD_DATA JSON,
    TOC BOOLEAN,
    TOC_DATA JSON,
    TDAH BOOLEAN,
    TDAH_DATA JSON,
    BIPOLARIDAD BOOLEAN,
    BIPOLARIDAD_DATA JSON,
    OTRO BOOLEAN,
    OTRO_DATA JSON,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE ANTECEDENTES_GINECOOBSTETRICOS (
    ID_PACIENTE INTEGER PRIMARY KEY NOT NULL,
    EDAD_PRIMERA_MENSTRUACION INTEGER,
    CICLOS_REGULARES BOOLEAN,
    MENSTRUACION_DOLOROSA BOOLEAN,
    MENSTRUACION_DOLOROSA_DATA JSON,
    NUM_EMBARAZOS INTEGER,
    NUM_PARTOS INTEGER,
    NUM_CESAREAS INTEGER,
    NUM_ABORTOS INTEGER,
    HISTERECTOMIA BOOLEAN,
    COMPLICACION_HISTERECTOMIA JSON,
    CIRUJIA BOOLEAN,
    COMPLICACION_CIRUJIA JSON,
    QUISTES_OVARICOS BOOLEAN,
    COMPLICACION_QUISTES JSON,
    RESECCION_MASAS BOOLEAN,
    COMPLICACION_RESECCION JSON,
    MIOMATOSIS BOOLEAN,
    COMPLICACION_MIOMATOSIS JSON,
    ENDOMETRIOSIS BOOLEAN,
    COMPLICACION_ENDOMETRIOSIS JSON,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE ANTECEDENTES_NO_PATOLOGICOS (
    ID_PACIENTE INTEGER PRIMARY KEY NOT NULL,
    TIPO_SANGRE VARCHAR(3) NOT NULL,
    FUMA BOOLEAN,
    FUMA_DATA JSON,
    BEBIDAS_ALCOHOLICAS BOOLEAN,
    BEBIDAS_ALCOHOLICAS_DATA JSON,
    DROGAS BOOLEAN,
    DROGAS_DATA JSON,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE SESION (
    TOKEN VARCHAR(100) PRIMARY KEY NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    FOREIGN KEY (EMAIL) REFERENCES USUARIO (EMAIL)
);

CREATE TABLE BITACORA (
    FECHA TIMESTAMP NOT NULL,
    USUARIO VARCHAR(50) NOT NULL,
    ACCION VARCHAR(50) NOT NULL,
    TABLA VARCHAR(50) NOT NULL,
    ID_REGISTRO VARCHAR(50) NOT NULL
);
