CREATE TABLE USUARIO (
    EMAIL VARCHAR(50) PRIMARY KEY,
    TIPO VARCHAR(20)
);

CREATE TABLE SEGURO (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50),
    ESTADO_ACTIVO BOOLEAN
);

CREATE TABLE PACIENTE (
    ID SERIAL PRIMARY KEY,
    CUI VARCHAR(24),
    CORREO VARCHAR(50),
    ES_MUJER BOOLEAN,
    NOMBRES VARCHAR(24),
    APELLIDOS VARCHAR(24),
    NOMBRE_CONTACTO1 VARCHAR(50),
    PARENTESCO_CONTACTO1 VARCHAR(24),
    TELEFONO_CONTACTO1 VARCHAR(20),
    NOMBRE_CONTACTO2 VARCHAR(50),
    PARENTESCO_CONTACTO2 VARCHAR(24),
    TELEFONO_CONTACTO2 VARCHAR(20),
    TIPO_SANGRE VARCHAR(3),
    DIRECCION VARCHAR(100),
    ID_SEGURO INTEGER,
    FECHA_NACIMIENTO DATE,
    TELEFONO VARCHAR(20),
    FOREIGN KEY (ID_SEGURO) REFERENCES SEGURO (ID)
);

CREATE TABLE ESTUDIANTE (
    CARNET VARCHAR(20),
    CARRERA VARCHAR(50),
    ID_PACIENTE INTEGER NOT NULL,
    PRIMARY KEY (CARNET),
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE COLABORADOR (
    CODIGO VARCHAR(20) PRIMARY KEY,
    AREA VARCHAR(50),
    ID_PACIENTE INTEGER NOT NULL,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE CONSULTA (
    ID SERIAL PRIMARY KEY,
    ID_PACIENTE INTEGER NOT NULL,
    FECHA TIMESTAMP,
    MOTIVO VARCHAR(100),
    FRECUENCIA_RESPIRATORIA VARCHAR(10),
    TEMPERATURA DOUBLE PRECISION,
    SATURACION_OXIGENO DOUBLE PRECISION,
    GLUCOMETRIA DOUBLE PRECISION,
    FRECUENCIA_CARDIACA DOUBLE PRECISION,
    PRESION_SISTOLICA INTEGER,
    PRESION_DIASTOLICA INTEGER,
    EVALUADOR VARCHAR(50),
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE DIAGNOSTICO (
    ID SERIAL PRIMARY KEY,
    ID_CONSULTA INTEGER NOT NULL,
    NOMBRE VARCHAR(50),
    TRATAMIENTO VARCHAR(100),
    FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTA (ID)
);

CREATE TABLE MEDICAMENTO (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50),
    CANTIDAD INTEGER,
    ID_CONSULTA INTEGER NOT NULL,
    FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTA (ID)
);

CREATE TABLE ANTECEDENTES_FAMILIARES (
    ID_PACIENTE INTEGER PRIMARY KEY,
    HIPERTENSION_ARTERIAL BOOLEAN,
    HIPERTENSION_ARTERIAL_DATA JSON,
    DIABETES_MELLITUS BOOLEAN,
    DIABETES_MELLITUS_DATA JSON,
    HIPOTIROIDISMO BOOLEAN,
    HIPOTIROIDISMO_DATA JSON,
    ASMA BOOLEAN,
    ASMA_DATA JSON,
    CONVULSIONES BOOLEAN,
    CONVULSIONES_DATA JSON,
    INFARTO_AGUDO_MIOCARDIO BOOLEAN,
    INFARTO_AGUDO_MIOCARDIO_DATA JSON,
    CANCER BOOLEAN,
    CANCER_DATA JSON,
    ENFERMEDADES_CARDIACAS BOOLEAN,
    ENFERMEDADES_CARDIACAS_DATA JSON,
    ENFERMEDADES_RENALES BOOLEAN,
    ENFERMEDADES_RENALES_DATA JSON,
    OTROS BOOLEAN,
    OTROS_DATA JSON,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE ANTECEDENTES_PERSONALES (
    ID_PACIENTE INTEGER PRIMARY KEY,
    HIPERTENSION_ARTERIAL BOOLEAN,
    HIPERTENSION_ARTERIAL_DATA JSON,
    DIABETES_MELLITUS BOOLEAN,
    DIABETES_MELLITUS_DATA JSON,
    HIPOTIROIDISMO BOOLEAN,
    HIPOTIROIDISMO_DATA JSON,
    ASMA BOOLEAN,
    ASMA_DATA JSON,
    CONVULSIONES BOOLEAN,
    CONVULSIONES_DATA JSON,
    INFARTO_AGUDO_MIOCARDIO BOOLEAN,
    INFARTO_AGUDO_MIOCARDIO_DATA JSON,
    CANCER BOOLEAN,
    CANCER_DATA JSON,
    ENFERMEDADES_CARDIACAS BOOLEAN,
    ENFERMEDADES_CARDIACAS_DATA JSON,
    ENFERMEDADES_RENALES BOOLEAN,
    ENFERMEDADES_RENALES_DATA JSON,
    OTROS BOOLEAN,
    OTROS_DATA JSON,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE ANTECEDENTES_ALERGICOS (
    ID_PACIENTE INTEGER PRIMARY KEY,
    MEDICAMENTO BOOLEAN,
    MEDICAMENTO_DATA JSON,
    COMIDA BOOLEAN,
    COMIDA_DATA JSON,
    POLVO BOOLEAN,
    POLVO_DATA JSON,
    POLEN BOOLEAN,
    POLEN_DATA JSON,
    CAMBIO_DE_CLIMA BOOLEAN,
    CAMBIO_DE_CLIMA_DATA JSON,
    ANIMALES BOOLEAN,
    ANIMALES_DATA JSON,
    OTROS BOOLEAN,
    OTROS_DATA JSON,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE ANTECEDENTES_QUIRURGICOS (
    ID_PACIENTE INTEGER PRIMARY KEY,
    ANTECEDENTE_QUIRURGICO BOOLEAN,
    ANTECEDENTE_QUIRURGICO_DATA JSON,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE ANTECEDENTES_TRAUMATOLOGICOS (
    ID_PACIENTE INTEGER PRIMARY KEY,
    ANTECEDENTE_TRAUMATOLOGICO BOOLEAN,
    ANTECEDENTE_TRAUMATOLOGICO_DATA JSON,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE ANTECEDENTES_PSIQUIATRICOS (
    ID_PACIENTE INTEGER PRIMARY KEY,
    DEPRESION BOOLEAN,
    DEPRESION_DATA JSON,
    ANSIEDAD BOOLEAN,
    ANSIEDAD_DATA JSON,
    TOC BOOLEAN,
    TOC_DATA JSON,
    TDAH BOOLEAN,
    TDAH_DATA JSON,
    BIPOLARIDAD BOOLEAN,
    BIPOLARIDAD_DATA JSON,
    OTRO BOOLEAN,
    OTRO_DATA JSON,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE ANTECEDENTES_GINECOOBSTETRICOS (
    ID_PACIENTE INTEGER PRIMARY KEY,
    EDAD_PRIMERA_MENSTRUACION INTEGER,
    CICLOS_REGULARES BOOLEAN,
    MENSTRUACION_DOLOROSA BOOLEAN,
    MENSTRUACION_DOLOROSA_DATA JSON,
    NUM_EMBARAZOS INTEGER,
    NUM_PARTOS INTEGER,
    NUM_CESAREAS INTEGER,
    NUM_ABORTOS INTEGER,
    HISTERECTOMIA BOOLEAN,
    COMPLICACION_HISTERECTOMIA JSON,
    CIRUJIA BOOLEAN,
    COMPLICACION_CIRUJIA JSON,
    QUISTES_OVARICOS BOOLEAN,
    COMPLICACION_QUISTES JSON,
    RESECCION_MASAS BOOLEAN,
    COMPLICACION_RESECCION JSON,
    MIOMATOSIS BOOLEAN,
    COMPLICACION_MIOMATOSIS JSON,
    ENDOMETRIOSIS BOOLEAN,
    COMPLICACION_ENDOMETRIOSIS JSON,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE ANTECEDENTES_NO_PATOLOGICOS (
    ID_PACIENTE INTEGER PRIMARY KEY,
    TIPO_SANGRE VARCHAR(3),
    FUMA BOOLEAN,
    FUMA_DATA JSON,
    BEBIDAS_ALCOHOLICAS BOOLEAN,
    BEBIDAS_ALCOHOLICAS_DATA JSON,
    DROGAS BOOLEAN,
    DROGAS_DATA JSON,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);

CREATE TABLE SESION (
    TOKEN VARCHAR(100) PRIMARY KEY,
    CREATED TIMESTAMP,
    EMAIL VARCHAR(50),
    FOREIGN KEY (EMAIL) REFERENCES USUARIO (EMAIL)
);

CREATE TABLE BITACORA (
    FECHA TIMESTAMP,
    USUARIO VARCHAR(50),
    ACCION VARCHAR(50),
    TABLA VARCHAR(50),
    ID_REGISTRO VARCHAR(50)
);
