---
name: Backend Linting and Tests
on:  # yamllint disable-line rule:truthy
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  linting:
    name: Backend checks
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nix develop .#cicdBackend --command bash {0}
        working-directory: sanitas_backend
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Installing dependencies
        run: npm install
      - name: Formatting
        run: npm run format:check
      - name: Linting
        run: npm run lint
      - name: Testing
        run: cd .. && nix run .#integrationTests
